version: '3.8'

services:
  better-minecraft:
    image: itzg/minecraft-server
    volumes:
    - ./better-mc/data:/data
    - ./better-mc/modpacks:/modpacks:ro
    - ./common:/extras
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/better-mc-pack-fabric-1-19-2-FIXED.zip
      VERSION: 1.19.2
      MOTD: "§l§9Viktor§r Goes To §l§cR§6a§ei§an§9b§do§5w §dL§9a§an§ed"
      WHITELIST_FILE: /extras/whitelist.json
      OPS_FILE: /extras/ops.json
      OVERRIDE_SERVER_PROPERTIES: true
      OVERRIDE_WHITELIST: true
      MAX_TICK_TIME: -1
      PVP: false
      MEMORY: 24G
      ENABLE_AUTOPAUSE: TRUE
    restart: unless-stopped
    ports:
      - "25565:25565"
  
  backup-better-minecraft:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "1h"
      MODPACK: "Better Minecraft"
      BACKUP_NAME: "better-minecraft"
      PAUSE_IF_NO_PLAYERS: true
      POST_BACKUP_SCRIPT: |
        echo "Completed backup for $$MODPACK!"
        echo "Cleaning up superfluous backups..."
        ls -t /backups | tail -n +4 | xargs rm --
        echo "Cleaned! Only three newest backups remain."
    volumes:
    - ./better-mc/data:/data:ro
    - /home/dropbox/Dropbox/backup/enderman.hideous.monster/better-mc:/backups
    restart: unless-stopped
    network_mode: "service:better-minecraft"
