version: '3.8'

services:
  create-above-and-beyond-survival:
    image: itzg/minecraft-server:java8-multiarch
    
    # May improve performance
    security_opt:
      - seccomp:unconfined 
    
    volumes:
    - ./create-above-and-beyond-survival/data:/data
    - ./create-above-and-beyond-survival/config:/config
    - ./create-above-and-beyond-survival/extras:/extras
    - ./create-above-and-beyond-survival/modpacks:/modpacks:ro
    - ./create-above-and-beyond-survival/worlds:/worlds
    - ./common:/common:ro
    
    environment:
      EULA: "true"
      TYPE: FORGE
      GENERIC_PACK: /modpacks/Above+and+Beyond-1.3-Server.zip
      VERSION: 1.16.5
      FORGEVERSION: 36.2.20
      MOTD: "§l§5Create: Above and Beyond§r (§cSurvival)"
      ICON: /extras/server-icon.png
      WORLD: /worlds/world
      WHITELIST_FILE: /common/whitelist.json
      OPS_FILE: /common/ops.json
      OVERRIDE_SERVER_PROPERTIES: true
      MAX_TICK_TIME: -1
      PVP: false
      MEMORY: 24G
      ENABLE_AUTOPAUSE: TRUE
      USE_MODPACK_START_SCRIPT: false
    restart: unless-stopped
    ports:
      - "25565:25565"
  
  backup-create-above-and-beyond-survival:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "1h"
      MODPACK: "Create - Above and Beyond - Survival Mode"
      BACKUP_NAME: "create-above-and-beyond-survival"
      PAUSE_IF_NO_PLAYERS: true
      POST_BACKUP_SCRIPT: |
        echo "Completed backup for $$MODPACK!"
        echo "Cleaning up superfluous backups..."
        ls -t /backups | tail -n +4 | xargs rm --        
        echo "Cleaned! Only three newest backups remain."
    volumes:
    - ./create-above-and-beyond-survival/data:/data:ro
    - /home/backup/create-above-and-beyond:/backups
    restart: unless-stopped
    network_mode: "service:create-above-and-beyond-survival"
